### PR TITLE
Install count per plugin/plugin version/jenkins version

### PR DESCRIPTION
**Pull request by batmat**
I was recently wondering what was the oldest Jenkins version using each of my plugins. This makes this information easier to find.

FWIW, it takes ~ 3 minutes to generate on my machine with the full DB as of today (~24GB).

Sample output:
```
{
    "jenkins-version-per-plugin-version": {
  ...
        "buildtriggerbadge": {
            "2.2": {
                "1.550": 1,
                "1.555": 1,
                "1.557": 3,
                "1.564": 1,
                "1.565.1": 2,
                "1.565.3": 5,
                "1.568": 1,
                "1.577": 1,
                "1.578": 1,
                "1.579": 1,
...            },
            "2.1": {
                "1.564": 1,
                "1.565.1": 1,
                "1.565.3": 1,
                "1.565.3_3": 2,
                "1.572": 1,
                "1.575": 1,
                "1.577": 1,
                "1.578": 1,
...
            },
            "2.1.0": {
                "1.572": 1
            }
        }
    }
}
```

### CODE REVIEW

**Comment by abayer** [comment]
Looks nifty to me. Reminds me that I need to add CSV output at some point...

**Comment by batmat** [comment]
Thanks @abayer !
Woops, noticed some typos, gonna force push them quickly so that I can look smarter.

**Comment by imod** [comment]
looks good to me...
the only question I have, is where you wanna consume and make it visible for developers?

**Comment by orrc** [comment]
It seems like it would be more useful to have *number* of installs per Jenkins version (or oldest Jenkins version)?

**Comment by batmat** [comment]
@imod I've thought a bit about it, and like for `capabilities.json` to my knowledge not accessible outside the raw file, I don't actually *plan to*.

But maybe I or someone else could indeed do some HTML/JS to render it nicely.

**Comment by imod** [comment]
@orrc , the numebr of installs per version is already available in e.g. http://stats.jenkins-ci.org/plugin-installation-trend/active-directory.stats.json as `installationsPerVersion`

**Comment by batmat** [comment]
FWIW I put a [full version here as an example](https://dl.dropboxusercontent.com/u/6790263/oldest-jenkins-version-per-plugin-version.json)

Just noticed that the version are sorted alphanumerically and not as versions should be (i.e. 1.9 incorrectly shows higher than 1.13, for workflow for example). Gonna see if it's worth to improve that.

**Comment by orrc** [comment]
Yeah, installs per plugin version is there, but installs per Jenkins version (per plugin version?) might be useful.  But probably not.

**Comment by imod** [comment]
oh, yeah - that's true, this is missing and for sure helpful to interpret the numbers correctly. e.g. who would keep compatibility for a Jenkins version which has only one installation?

**Comment by batmat** [comment]
OK. IIUC the idea would be to replace the current Jenkins oldest version
with a new subnode with basically a map of : "Jenkins version: number (of
installs of the enclosing plugin version)" ?
Le 2 févr. 2016 8:28 AM, "Dominik Bartholdi" <notifications@github.com> a
écrit :

**Comment by imod** [comment]
yeah, I think that would make sense. I would also rename `oldestJenkinsPerPluginVersion` to `jenkinsPerPluginVersion` - I don't think 'oldest' adds any additional info for the user WDYT?

**Comment by batmat** [comment]
I've got something that works on my machine:
(Obviously a lot more verbose)

Is that the type of thing you had in mind?

```
...
"buildtriggerbadge": {
            "2.2": {
                "1.550": 1,
                "1.555": 1,
                "1.557": 3,
                "1.564": 1,
                "1.565.1": 2,
                "1.565.3": 5,
                "1.568": 1,
                "1.577": 1,
                "1.578": 1,
                "1.579": 1,
                "1.580.1": 2,
                "1.580.2": 3,
                "1.580.3": 1,
                "1.581": 1,
                "1.584": 1,
                "1.585": 1,
                "1.591": 1,
                "1.592": 1,
                "1.593": 2,
                "1.595": 3,
                "1.596": 3,
                "1.596.2": 5,
                "1.596.2_4": 5,
                "1.596.3": 3,
                "1.598": 5,
                "1.599": 2,
                "1.602": 3,
                "1.604": 1,
                "1.605": 2,
                "1.606": 1,
                "1.607": 1,
                "1.608": 1,
                "1.609": 4,
                "1.609.1": 10,
                "1.609.2": 7,
                "1.609.3": 31,
                "1.610": 2,
                "1.611": 4,
                "1.614": 8,
                "1.615": 4,
                "1.616": 5,
                "1.617": 16,
                "1.618": 2,
                "1.619": 5,
                "1.620": 5,
                "1.621": 3,
                "1.622": 3,
                "1.623": 2,
                "1.624": 9,
                "1.625": 4,
                "1.625.1": 37,
                "1.625.2": 70,
                "1.625.3": 91,
                "1.626": 2,
                "1.627": 13,
                "1.628": 10,
                "1.629": 5,
                "1.630": 13,
                "1.631": 12,
                "1.632": 18,
                "1.633": 9,
                "1.634": 24,
                "1.635": 26,
                "1.636": 22,
                "1.637": 13,
                "1.638": 105,
                "1.639": 88,
                "1.640": 24,
                "1.641": 60,
                "1.642": 120,
                "1.643": 128
            },
            "2.1": {
                "1.564": 1,
                "1.565.1": 1,
                "1.565.3": 1,
                "1.565.3_3": 2,
                "1.572": 1,
                "1.575": 1,
                "1.577": 1,
                "1.578": 1,
                "1.592": 1,
                "1.594": 1,
                "1.596": 1,
                "1.596.2": 2,
                "1.596.2_4": 3,
                "1.597": 1,
                "1.599": 3,
                "1.602": 1,
                "1.605": 1,
                "1.606": 1,
                "1.607": 1,
                "1.609.1": 4,
                "1.609.2": 3,
                "1.609.3": 15,
                "1.611": 3,
                "1.615": 1,
                "1.617": 6,
                "1.618": 1,
                "1.619": 3,
                "1.620": 4,
                "1.622": 7,
                "1.623": 2,
                "1.624": 11,
                "1.625": 1,
                "1.625.1": 3,
                "1.625.2": 5,
                "1.625.3": 1,
                "1.626": 5,
                "1.627": 13,
                "1.628": 14,
                "1.629": 13,
                "1.630": 9,
                "1.631": 15,
                "1.632": 12,
                "1.633": 2,
                "1.635": 1,
                "1.638": 5,
                "1.639": 6,
                "1.640": 2,
                "1.642": 1,
                "1.643": 3
            },
            "2.0": {
                "1.485": 1,
                "1.511": 1,
                "1.512": 1,
                "1.515": 1,
                "1.524": 1,
                "1.526": 1,
                "1.532.2": 1,
                "1.547": 1,
                "1.554": 1,
                "1.554.1": 2,
                "1.554.2": 1,
                "1.557": 1,
                "1.565": 1,
                "1.565.1": 2,
                "1.565.3": 6,
                "1.565.3_3": 4,
                "1.566": 2,
                "1.571": 2,
                "1.572": 1,
                "1.574": 1,
                "1.577": 1,
                "1.578": 1,
                "1.579": 1,
                "1.580": 1,
                "1.580.1": 2,
                "1.580.2": 3,
                "1.580.3": 5,
                "1.581": 1,
                "1.582": 1,
                "1.583": 5,
                "1.584": 3,
                "1.585": 1,
                "1.586": 1,
                "1.588": 2,
                "1.589": 4,
                "1.591": 2,
                "1.592": 2,
                "1.593": 6,
                "1.594": 3,
                "1.595": 4,
                "1.596": 7,
                "1.596.1": 5,
                "1.596.2": 41,
                "1.596.2_2": 1,
                "1.596.2_4": 16,
                "1.596.3": 5,
                "1.597": 1,
                "1.598": 14,
                "1.599": 19,
                "1.600": 1,
                "1.601": 2,
                "1.602": 12,
                "1.604": 1,
                "1.605": 7,
                "1.606": 5,
                "1.607": 9,
                "1.608": 11,
                "1.609": 27,
                "1.609.1": 61,
                "1.609.2": 15,
                "1.609.3": 7,
                "1.610": 14,
                "1.611": 14,
                "1.612": 13,
                "1.613": 12,
                "1.614": 11,
                "1.615": 10,
                "1.616": 15,
                "1.617": 40,
                "1.618": 16,
                "1.619": 22,
                "1.620": 26,
                "1.621": 2,
                "1.622": 11,
                "1.623": 13,
                "1.624": 18,
                "1.625": 2,
                "1.625.1": 2,
                "1.625.2": 7,
                "1.625.3": 18,
                "1.626": 12,
                "1.627": 4,
                "1.628": 3,
                "1.629": 2,
                "1.630": 6,
                "1.631": 3,
                "1.632": 5,
                "1.633": 1,
                "1.634": 8,
                "1.635": 2,
                "1.636": 4,
                "1.637": 4,
                "1.638": 13,
                "1.639": 5,
                "1.641": 6,
                "1.642": 15,
                "1.643": 7
            },
            "1.4-2-INTEL-4": {
                "1.596.2": 6,
                "1.596.2-INTEL-4": 1,
                "1.596.2-INTEL-5": 1
            },
            "1.4": {
                "1.512": 1,
                "1.559": 1,
                "1.578": 1,
                "1.580.2": 3,
                "1.580.3": 1,
                "1.582": 1,
                "1.585": 1,
                "1.588": 1,
                "1.596": 1,
                "1.596.1": 1,
                "1.598": 6,
                "1.609.2": 1,
                "1.609.3": 2,
                "1.617": 1,
                "1.630": 1,
                "1.638": 1
            },
            "1.3": {
                "1.532": 1,
                "1.539": 1,
                "1.543": 1,
                "1.544": 1,
                "1.550": 19,
                "1.554.3": 1,
                "1.558": 1,
                "1.560": 1,
                "1.564": 1,
                "1.565.2": 1,
                "1.565.3": 5,
                "1.565.3_2": 1,
                "1.566": 1,
                "1.568": 2,
                "1.570": 1,
                "1.571": 1,
                "1.572": 2,
                "1.574": 3,
                "1.575": 2,
                "1.577": 2,
                "1.578": 1,
                "1.579": 4,
                "1.580": 4,
                "1.580.1": 21,
                "1.580.2": 9,
                "1.580.3": 5,
                "1.581": 7,
                "1.582": 5,
                "1.583": 6,
                "1.584": 6,
                "1.585": 8,
                "1.586": 5,
                "1.587": 3,
                "1.588": 8,
                "1.589": 4,
                "1.590": 10,
                "1.591": 2,
                "1.593": 13,
                "1.594": 13,
                "1.595": 4,
                "1.596": 6,
                "1.596.1": 1,
                "1.596.2": 4,
                "1.597": 2,
                "1.598": 10,
                "1.602": 2,
                "1.606": 2,
                "1.607": 1,
                "1.609.1": 1,
                "1.609.2": 1,
                "1.609.3": 1,
                "1.611": 1,
                "1.614": 1,
                "1.617": 2,
                "1.618": 2,
                "1.619": 1,
                "1.624": 1,
                "1.625.2": 6,
                "1.625.3": 2,
                "1.628": 1,
                "1.629": 1,
                "1.631": 1,
                "1.632": 1,
                "1.633": 1,
                "1.634": 1,
                "1.638": 3,
                "1.639": 2,
                "1.642": 3
            },
            "1.2": {
                "1.444": 1,
                "1.512": 1,
                "1.526": 1,
                "1.532.3": 3,
                "1.537": 1,
                "1.539": 2,
                "1.541": 1,
                "1.544": 2,
                "1.552": 2,
                "1.554.1": 2,
                "1.554.2": 1,
                "1.554.3": 3,
                "1.555": 3,
                "1.557": 1,
                "1.558": 1,
                "1.562": 6,
                "1.563": 5,
                "1.564": 2,
                "1.565": 4,
                "1.565.1": 7,
                "1.565.2": 7,
                "1.565.3": 1,
                "1.565.3_1": 1,
                "1.565.3_2": 1,
                "1.565.3_3": 1,
                "1.566": 1,
                "1.567": 3,
                "1.568": 1,
                "1.569": 2,
                "1.570": 5,
                "1.571": 4,
                "1.572": 3,
                "1.573": 4,
                "1.574": 8,
                "1.575": 3,
                "1.576": 3,
                "1.577": 6,
                "1.578": 6,
                "1.580": 2,
                "1.580.1": 1,
                "1.580.2": 2,
                "1.581": 3,
                "1.582": 1,
                "1.583": 1,
                "1.586": 1,
                "1.589": 1,
                "1.590": 2,
                "1.593": 2,
                "1.594": 2,
                "1.595": 2,
                "1.596": 1,
                "1.596.2": 2,
                "1.596.2_4": 8,
                "1.598": 15,
                "1.599": 2,
                "1.601": 1,
                "1.605": 3,
                "1.606": 1,
                "1.609.1": 1,
                "1.609.2": 3,
                "1.609.3": 2,
                "1.610": 2,
                "1.611": 5,
                "1.612": 1,
                "1.617": 1,
                "1.623": 1,
                "1.625.2": 1,
                "1.626": 2,
                "1.628": 2,
                "1.629": 2,
                "1.630": 1,
                "1.634": 1,
                "1.638": 2,
                "1.639": 1,
                "1.643": 1
            },
            "1.1": {
                "1.487": 1,
                "1.490": 1,
                "1.492": 1,
                "1.509.2": 2,
                "1.509.4": 1,
                "1.514": 1,
                "1.516": 1,
                "1.519": 1,
                "1.523": 3,
                "1.524": 1,
                "1.528": 2,
                "1.532": 1,
                "1.532.2": 4,
                "1.533": 1,
                "1.534": 4,
                "1.535": 1,
                "1.536": 1,
                "1.537": 15,
                "1.538": 4,
                "1.539": 5,
                "1.540": 2,
                "1.541": 1,
                "1.542": 3,
                "1.543": 3,
                "1.544": 4,
                "1.546": 1,
                "1.549": 5,
                "1.550": 3,
                "1.551": 2,
                "1.552": 1,
                "1.553": 2,
                "1.554": 4,
                "1.555": 2,
                "1.556": 5,
                "1.557": 2,
                "1.558": 9,
                "1.559": 2,
                "1.560": 1,
                "1.563": 3,
                "1.564": 1,
                "1.565": 1,
                "1.565.1": 1,
                "1.565.2": 1,
                "1.566": 2,
                "1.567": 1,
                "1.568": 2,
                "1.570": 3,
                "1.573": 1,
                "1.574": 1,
                "1.577": 5,
                "1.579": 2,
                "1.580.3": 1,
                "1.581": 1,
                "1.582": 1,
                "1.583": 1,
                "1.584": 1,
                "1.589": 3,
                "1.593": 1,
                "1.594": 3,
                "1.595": 3,
                "1.596": 1,
                "1.596.1": 1,
                "1.596.2": 2,
                "1.597": 1,
                "1.599": 2,
                "1.600": 1,
                "1.602": 2,
                "1.607": 1,
                "1.609": 1,
                "1.609.2": 2,
                "1.609.3": 1,
                "1.611": 1,
                "1.612": 1,
                "1.614": 1,
                "1.617": 2,
                "1.621": 2,
                "1.624": 2,
                "1.625.3": 1,
                "1.626": 1,
                "1.629": 6,
                "1.630": 1,
                "1.631": 2,
                "1.635": 2,
                "1.636": 2,
                "1.638": 1,
                "1.639": 5,
                "1.641": 1,
                "1.642": 2
            },
            "1.0": {
                "1.480": 1,
                "1.480.3": 1,
                "1.500": 1,
                "1.504": 1,
                "1.505": 2,
                "1.506": 1,
                "1.508": 2,
                "1.509": 2,
                "1.509.1": 2,
                "1.511": 1,
                "1.512": 1,
                "1.513": 2,
                "1.514": 4,
                "1.518": 1,
                "1.519": 1,
                "1.522": 1,
                "1.523": 5,
                "1.525": 1,
                "1.529": 1,
                "1.532": 1,
                "1.532.3": 2,
                "1.533": 1,
                "1.535": 1,
                "1.542": 1,
                "1.544": 1,
                "1.546": 1,
                "1.552": 1,
                "1.554.1": 1,
                "1.556": 1,
                "1.564": 1,
                "1.565": 1,
                "1.575": 2,
                "1.580.2": 1,
                "1.582": 1,
                "1.590": 1,
                "1.592": 1,
                "1.596.2": 2,
                "1.597": 1,
                "1.602": 1,
                "1.616": 1,
                "1.617": 1,
                "1.623": 1,
                "1.625.2": 1,
                "1.625.3": 2
            },
            "0.9": {
                "1.466.1": 1,
                "1.472": 1,
                "1.480.3": 3,
                "1.492": 1,
                "1.494": 1,
                "1.498": 1,
                "1.500": 1,
                "1.509.4": 3,
                "1.526": 1,
                "1.534": 1,
                "1.544": 1,
                "1.547": 1,
                "1.553": 1,
                "1.558": 1,
                "1.565.3": 1,
                "1.573": 1,
                "1.583": 1,
                "1.606": 1
            },
            "0.8": {
                "1.620": 1
            },
            "0.6": {
                "1.482": 1
            }
        },
        "built-on-column": {
            "1.1": {
                "1.424.6": 3,
                "1.428": 1,
                "1.436": 1,
                "1.441": 1,
                "1.447.1": 1,
                "1.451": 2,
                "1.452": 1,
                "1.454": 2,
                "1.455": 5,
                "1.457": 1,
                "1.458": 1,
                "1.461": 1,
                "1.462": 1,
                "1.466": 3,
                "1.466.1": 1,
                "1.466.2": 1,
                "1.470": 2,
                "1.475": 2,
                "1.478": 2,
                "1.480": 1,
                "1.480.2": 7,
                "1.480.3": 1,
                "1.481": 1,
                "1.482": 1,
                "1.484": 2,
                "1.487": 1,
                "1.488": 1,
                "1.489": 1,
                "1.491": 2,
                "1.495": 1,
                "1.498": 2,
                "1.499": 1,
                "1.500": 1,
                "1.501": 1,
                "1.505": 1,
                "1.507": 1,
                "1.508": 2,
                "1.509.1": 1,
                "1.509.2": 2,
                "1.509.4": 9,
                "1.510": 1,
                "1.512": 1,
                "1.514": 3,
                "1.516": 2,
                "1.521": 2,
                "1.522": 1,
                "1.523": 3,
                "1.525": 2,
                "1.526": 1,
                "1.529": 2,
                "1.530": 2,
                "1.532": 1,
                "1.532.1": 3,
                "1.532.1.JENKINS-19453": 1,
                "1.532.2": 7,
                "1.532.3": 3,
                "1.533": 2,
                "1.534": 2,
                "1.535": 2,
                "1.536": 3,
                "1.537": 1,
                "1.538": 2,
                "1.539": 2,
                "1.541": 1,
                "1.542": 4,
                "1.543": 2,
                "1.544": 1,
                "1.545": 2,
                "1.546": 3,
                "1.547": 1,
                "1.548": 1,
                "1.549": 2,
                "1.551": 3,
                "1.552": 2,
                "1.553": 7,
                "1.554": 2,
                "1.554.1": 3,
                "1.554.2": 1,
                "1.554.3": 6,
                "1.555": 1,
                "1.556": 1,
                "1.557": 2,
                "1.558": 2,
                "1.559": 2,
                "1.560": 1,
                "1.561": 1,
                "1.563": 4,
                "1.564": 1,
                "1.565.1": 5,
                "1.565.2": 9,
                "1.565.3": 11,
                "1.565.3_3": 1,
                "1.567": 2,
                "1.568": 44,
                "1.569": 6,
                "1.570": 4,
                "1.571": 1,
                "1.572": 1,
                "1.573": 7,
                "1.574": 9,
                "1.575": 3,
                "1.577": 3,
                "1.578": 3,
                "1.579": 6,
                "1.580": 4,
                "1.580.1": 9,
                "1.580.1.JENKINS-26201-workspace-lock-1": 1,
                "1.580.2": 6,
                "1.580.3": 24,
                "1.581": 7,
                "1.582": 5,
                "1.583": 14,
                "1.584": 5,
                "1.585": 4,
                "1.586": 4,
                "1.587": 3,
                "1.588": 4,
                "1.589": 5,
                "1.590": 9,
                "1.591": 3,
                "1.592": 6,
                "1.593": 3,
                "1.594": 5,
                "1.595": 8,
                "1.596": 16,
                "1.596.1": 8,
                "1.596.2": 10,
                "1.596.3": 5,
                "1.597": 3,
                "1.598": 12,
                "1.599": 7,
                "1.600": 11,
                "1.601": 1,
                "1.602": 3,
                "1.604": 1,
                "1.605": 3,
                "1.606": 8,
                "1.607": 7,
                "1.608": 5,
                "1.609": 11,
                "1.609.1": 23,
                "1.609.2": 11,
                "1.609.3": 40,
                "1.610": 3,
                "1.611": 11,
                "1.612": 4,
                "1.613": 9,
                "1.614": 11,
                "1.616": 5,
                "1.617": 25,
                "1.618": 6,
                "1.619": 10,
                "1.620": 11,
                "1.621": 2,
                "1.622": 4,
                "1.623": 6,
                "1.624": 10,
                "1.625": 4,
                "1.625.1": 13,
                "1.625.2": 41,
                "1.625.3": 38,
                "1.626": 7,
                "1.627": 4,
                "1.628": 7,
                "1.629": 12,
                "1.630": 8,
                "1.631": 10,
                "1.632": 12,
                "1.633": 4,
                "1.634": 12,
                "1.635": 10,
                "1.636": 12,
                "1.637": 9,
                "1.638": 54,
                "1.639": 31,
                "1.640": 9,
                "1.641": 15,
                "1.642": 32,
                "1.643": 21
            },
            "1.0": {
                "1.410": 1,
                "1.447": 1,
                "1.509.4": 1,
                "1.532": 1
            }
        },
        "bulk-builder": {
            "1.5": {
                "1.410 (private)": 1,
                "1.411 (private)": 1,
                "1.455": 1,
                "1.456": 1,
                "1.458": 2,
                "1.462": 1,
                "1.463": 2,
                "1.466": 1,
                "1.466.1": 1,
                "1.467": 1,
                "1.469": 1,
                "1.470": 1,
                "1.474": 1,
                "1.475": 4,
                "1.478": 4,
                "1.480.2": 1,
                "1.480.3": 5,
                "1.481": 1,
                "1.482": 1,
                "1.483": 2,
                "1.484": 2,
                "1.485": 1,
                "1.486": 1,
                "1.490": 1,
                "1.491": 1,
                "1.492": 2,
                "1.496": 4,
                "1.499": 2,
                "1.509.1": 4,
                "1.509.2": 3,
                "1.509.2.JENKINS-14362-jzlib": 1,
                "1.509.3": 12,
                "1.509.4": 8,
                "1.510": 2,
                "1.511": 1,
                "1.512": 1,
                "1.513": 1,
                "1.514": 3,
                "1.515": 2,
                "1.516": 2,
                "1.517": 1,
                "1.518": 2,
                "1.519": 1,
                "1.520": 4,
                "1.521": 2,
                "1.522": 6,
                "1.523": 3,
                "1.525": 5,
                "1.526": 2,
                "1.527": 1,
                "1.529": 2,
                "1.532.1": 2,
                "1.532.2": 6,
                "1.532.2-AMADEUS-2": 3,
                "1.532.3": 5,
                "1.533": 2,
                "1.534": 5,
                "1.535": 3,
                "1.536": 4,
                "1.537": 4,
                "1.538": 6,
                "1.539": 3,
                "1.540": 2,
                "1.541": 1,
                "1.542": 1,
                "1.543": 2,
                "1.544": 4,
                "1.545": 1,
                "1.546": 3,
                "1.547": 1,
                "1.548": 1,
                "1.549": 8,
                "1.550": 2,
                "1.551": 3,
                "1.552": 1,
                "1.553": 5,
                "1.554": 4,
                "1.554.1": 3,
                "1.554.2": 2,
                "1.554.3": 4,
                "1.555": 4,
                "1.556": 6,
                "1.557": 4,
                "1.558": 4,
                "1.559": 1,
                "1.561": 2,
                "1.563": 4,
                "1.564": 2,
                "1.565": 17,
                "1.565.1": 7,
                "1.565.2": 34,
                "1.565.3": 11,
                "1.566": 6,
                "1.567": 5,
                "1.568": 42,
                "1.569": 3,
                "1.570": 13,
                "1.571": 7,
                "1.572": 2,
                "1.573": 5,
                "1.574": 15,
                "1.575": 8,
                "1.576": 1,
                "1.577": 4,
                "1.578": 4,
                "1.579": 3,
                "1.580": 3,
                "1.580.1": 10,
                "1.580.2": 6,
                "1.580.3": 15,
                "1.581": 4,
                "1.582": 4,
                "1.583": 11,
                "1.584": 7,
                "1.585": 1,
                "1.586": 3,
                "1.587": 1,
                "1.588": 16,
                "1.589": 7,
                "1.590": 8,
                "1.591": 2,
                "1.592": 9,
                "1.593": 14,
                "1.594": 12,
                "1.595": 7,
                "1.596": 16,
                "1.596.1": 11,
                "1.596.2": 28,
                "1.596.2-INTEL-4": 1,
                "1.596.2-INTEL-5": 1,
                "1.596.3": 30,
                "1.597": 5,
                "1.598": 16,
                "1.599": 16,
                "1.601": 7,
                "1.602": 6,
                "1.604": 1,
                "1.605": 2,
                "1.606": 6,
                "1.607": 7,
                "1.608": 4,
                "1.609": 19,
                "1.609.1": 30,
                "1.609.2": 20,
                "1.609.3": 27,
                "1.610": 14,
                "1.611": 15,
                "1.612": 15,
                "1.613": 12,
                "1.614": 4,
                "1.615": 5,
                "1.616": 7,
                "1.617": 21,
                "1.618": 12,
                "1.619": 11,
                "1.620": 15,
                "1.621": 5,
                "1.622": 4,
                "1.623": 3,
                "1.624": 15,
                "1.625": 3,
                "1.625.1": 15,
                "1.625.2": 37,
                "1.625.3": 41,
                "1.626": 14,
                "1.627": 11,
                "1.628": 13,
                "1.629": 14,
                "1.630": 23,
                "1.631": 20,
                "1.632": 13,
                "1.633": 4,
                "1.634": 23,
                "1.635": 16,
                "1.636": 16,
                "1.637": 12,
                "1.638": 65,
                "1.639": 41,
                "1.640": 12,
                "1.641": 31,
                "1.642": 66,
                "1.643": 45
            },
            "1.4": {
                "1.441": 1,
                "1.447": 1,
                "1.538": 1,
                "1.590": 1
            },
            "1.3": {
                "1.438": 1,
                "1.451": 1,
                "1.490": 1,
                "1.532.2": 1,
                "1.546": 1,
                "1.554.2": 1,
                "1.564": 1
            },
            "1.2": {
                "1.413": 1,
                "1.433": 1,
                "1.466": 1,
                "1.534": 1
            },
            "1.0": {
                "1.409": 1,
                "1.421": 1,
                "1.492": 1,
                "1.502": 1,
                "1.642": 1
            },
            "0.8": {
                "1.405": 1,
                "1.408": 1
            },
            "0.7": {
                "1.565.2": 1
            },
            "0.6": {
                "1.427": 1
            },
            "0.5": {
                "1.434": 1
            }
        },
        "bumblebee": {
            "4.0.0": {
                "1.590": 1,
                "1.602": 1,
                "1.612": 1,
                "1.617": 1,
                "1.625.1": 1,
                "1.625.2": 2,
                "1.625.3": 1,
                "1.627": 2,
                "1.629": 1,
                "1.635": 2,
                "1.636": 1,
                "1.638": 8,
                "1.642": 2,
                "1.643": 4
            },
            "3.0.3": {
                "1.509.4": 1,
                "1.532.1": 1,
                "1.549": 1,
                "1.555": 1,
                "1.564": 1,
                "1.565": 1,
                "1.565.3": 1,
                "1.574": 1,
                "1.577": 1,
                "1.579": 1,
                "1.580": 2,
                "1.580.2": 1,
                "1.592": 1,
                "1.596.3": 1,
                "1.597": 1,
                "1.602": 2,
                "1.604": 1,
                "1.606": 1,
                "1.607": 1,
                "1.608": 2,
                "1.609": 3,
                "1.609.3": 3,
                "1.611": 1,
                "1.612": 1,
                "1.614": 2,
                "1.615": 1,
                "1.616": 2,
                "1.617": 1,
                "1.618": 1,
                "1.619": 2,
                "1.620": 2,
                "1.624": 1,
                "1.627": 3,
                "1.629": 1,
                "1.630": 1,
                "1.632": 1,
                "1.633": 1,
                "1.636": 1,
                "1.638": 2,
                "1.639": 3
            },
            "2.1.0": {
                "1.572": 1
            }
        }
```

**Comment by batmat** [comment]
Your wishes have just come true @orrc @imod :smile: 
Just force pushed the modified version.

**Comment by imod** [comment]
:+1:

**Comment by batmat** [comment]
Hi! If you don't have any remarks left, then  ? 
:smile:

**Comment by imod** [comment]
@batmat sorry for the delay!!!!

**Comment by batmat** [comment]
No problem. Thanks for merging!
Le 22 févr. 2016 5:22 PM, "Dominik Bartholdi" <notifications@github.com> a
écrit :

**Pull request merged**
